# Generated by Django 5.2.8 on 2025-12-03 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_department'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseschedule',
            name='teacher',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='courseschedule',
            unique_together={('course', 'teacher', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
